# This is a basic workflow to help you get started with Actions

name: LaTeX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        # The root LaTeX file to be compiled
        root_file: beamer-slides.tex
        # The working directory for the LaTeX engine
        working_directory: . # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        # Install extra packages by apk
        extra_system_packages: nano # optional
        # Arbitrary bash codes to be executed before compiling LaTeX documents
        # pre_compile: # optional
        # Arbitrary bash codes to be executed after compiling LaTeX documents
        # post_compile: # optional
        # Instruct latexmk to enable --shell-escape
        latexmk_shell_escape: true # optional
        # Instruct latexmk to use LuaLaTeX
        latexmk_use_lualatex: false # optional
        # Instruct latexmk to use XeLaTeX
        #latexmk_use_xelatex: true # optional
    
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: ./beamer-slides.pdf
